"""
Django settings for settings project.

Generated by 'django-admin startproject' using Django 2.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
from dotenv import load_dotenv


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Calea către fișierul .env
dotenv_path = os.path.join(BASE_DIR, '.env')
load_dotenv(dotenv_path)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', default='unsafe-secret-key')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', default='')

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'apps.access',
    # 'apps.digiapp',
]

ALLOWED_HOSTS = ["localhost", "digitizare.math.md", "math.md",
                 "ngrok.io", "uuj2kn6s.ngrok.app", "127.0.0.1", "81.180.76.233"]
# CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:8080",
#     "http://127.0.0.1:8000",
#     "http://127.0.0.1:3000",
#     'http://localhost:3000',
#     'http://localhost:8000',
#     'http://localhost:8080',
#     'https://ngrok.io',
#     'https://a1ef-81-180-76-251.eu.ngrok.io',
#     'https://digitizare.math.md'
# ]

CORS_ORIGIN_WHITELIST = [
    'http://localhost:3000',
    'http://localhost:8000',
    'http://localhost:8080',
    'https://ngrok.io',
    'https://uuj2kn6s.ngrok.app',
    'https://digitizare.math.md'
]

CSRF_TRUSTED_ORIGINS = ['https://uuj2kn6s.ngrok.app', 'http://localhost:3000',
                        'http://localhost:8000', 'http://localhost:8080', 'https://ngrok.io']

CORS_ALLOW_METHODS = (
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
)

CORS_ALLOW_HEADERS = (
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apps.access.custom_cors_middleware.CustomCorsMiddleware'
]

ROOT_URLCONF = 'settings.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'settings.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Chisinau'

USE_I18N = True

USE_L10N = True

USE_TZ = True


STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# -------------------------------------------------------------------
# External services configuration (used by health checks & pipeline)
# -------------------------------------------------------------------

# ABBYY FineReader Hot Folder paths.
# INPUT  = folder watched by FineReader where images are dropped.
# OUTPUT = folder where FineReader writes recognized .txt/.pdf results.
FINEREADER_INPUT_DIR = os.getenv(
    'FINEREADER_INPUT_DIR', default=MEDIA_ROOT)
FINEREADER_OUTPUT_DIR = os.getenv(
    'FINEREADER_OUTPUT_DIR', default=os.path.join(MEDIA_ROOT, 'ocr'))

# Transliteration service endpoint.
TRANSLITERA_URL = os.getenv(
    'TRANSLITERA_URL', default='https://translitera.cc/ProcessServlet')

# Publishing platform endpoint.
PUBLISH_URL = os.getenv(
    'PUBLISH_URL', default='https://digi.emoldova.org/api/drafts')

# AWS S3 configuration.
AWS_ACCESS_KEY = os.getenv('AWS_ACCESS_KEY', default='')
AWS_SECRET_KEY = os.getenv('AWS_SECRET_KEY', default='')
AWS_S3_BUCKET = os.getenv('AWS_S3_BUCKET', default='emoldova.bucket')

# How long (seconds) health-check results are cached before re-probing.
HEALTH_CACHE_TTL = int(os.getenv('HEALTH_CACHE_TTL', default='12'))
# Per-service network timeout (seconds) for health probes.
HEALTH_PROBE_TIMEOUT = float(os.getenv('HEALTH_PROBE_TIMEOUT', default='5'))

