# Generated by Django 2.1.3 on 2018-11-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_register_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
