# Generated by Django 4.1.4 on 2022-12-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0006_rename_exceptiondictionary_exceptiondictionaryentry_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exceptiondictionaryentry',
            old_name='word',
            new_name='translit_word',
        ),
        migrations.AlterField(
            model_name='exceptiondictionaryentry',
            name='modified_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
