# Generated by Django 4.0.2 on 2022-12-23 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0008_rename_translit_word_exceptiondictionaryentry_correct_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alphabet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('added_by', models.CharField(max_length=100)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Alfabete',
                'verbose_name_plural': 'Alfabet',
            },
        ),
        migrations.CreateModel(
            name='ExceptionDictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('added_by', models.CharField(max_length=100)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Exception Dictionary',
                'verbose_name_plural': 'Exception Dictionaries',
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('added_by', models.CharField(max_length=100)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Perioadă',
                'verbose_name_plural': 'Perioade',
            },
        ),
        migrations.CreateModel(
            name='PostprocessingEngine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('added_by', models.CharField(max_length=100)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Motor de postprocesare',
                'verbose_name_plural': 'Motoare de postprocesare',
            },
        ),
        migrations.CreateModel(
            name='PreprocessingEngine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('added_by', models.CharField(max_length=100)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Preprocessing Engine',
                'verbose_name_plural': 'Preprocessing Engines',
            },
        ),
        migrations.RemoveField(
            model_name='file',
            name='image',
        ),
        migrations.AddField(
            model_name='file',
            name='ocr_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='original_image_S3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='original_image_local',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='preprocessed_image_S3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='preprocessed_image_local',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='transliterated_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='exceptiondictionaryentry',
            name='period',
        ),
        migrations.CreateModel(
            name='PreprocessingEngineModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('module_file', models.FileField(blank=True, null=True, upload_to='preprocessing_modules/')),
                ('options_object', models.TextField(blank=True, null=True)),
                ('added_by', models.CharField(max_length=100)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access.preprocessingengine')),
            ],
            options={
                'verbose_name': 'Motor de postprocesare',
                'verbose_name_plural': 'Motoare de postprocesare',
            },
        ),
        migrations.CreateModel(
            name='PostprocessingEngineModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('module_file', models.FileField(blank=True, null=True, upload_to='postprocessing_modules/')),
                ('options_object', models.TextField(blank=True, null=True)),
                ('added_by', models.CharField(max_length=100)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access.postprocessingengine')),
            ],
            options={
                'verbose_name': 'Postprocessing Engine Module',
                'verbose_name_plural': 'Postprocessing Engine Modules',
            },
        ),
        migrations.CreateModel(
            name='OCRModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_file', models.FileField(blank=True, null=True, upload_to='ocr_models/')),
                ('dataset', models.CharField(blank=True, max_length=200, null=True)),
                ('dataset_size', models.IntegerField(blank=True, null=True)),
                ('added_by', models.CharField(max_length=100)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('alphabet', models.ManyToManyField(to='access.Alphabet')),
                ('period', models.ManyToManyField(to='access.Period')),
            ],
            options={
                'verbose_name': 'OCR Model',
                'verbose_name_plural': 'OCR Models',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('digital_object', models.TextField()),
                ('added_by', models.CharField(max_length=100)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('alphabet', models.ManyToManyField(to='access.Alphabet')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access.file')),
                ('ocr_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access.ocrmodel')),
                ('period', models.ManyToManyField(to='access.Period')),
                ('postprocessing_engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access.postprocessingengine')),
                ('preprocessing_engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access.preprocessingengine')),
            ],
            options={
                'verbose_name': 'Document digitalizat',
                'verbose_name_plural': 'Documente digitalizate',
            },
        ),
        migrations.AddField(
            model_name='exceptiondictionaryentry',
            name='alphabet',
            field=models.ManyToManyField(to='access.Alphabet'),
        ),
        migrations.AddField(
            model_name='exceptiondictionaryentry',
            name='exception_dictionary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='access.exceptiondictionary'),
        ),
        migrations.AddField(
            model_name='exceptiondictionaryentry',
            name='period',
            field=models.ManyToManyField(to='access.Period'),
        ),
    ]
