# Generated by Django 4.0.2 on 2022-12-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0010_alter_exceptiondictionary_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='alphabet',
            field=models.ManyToManyField(blank=True, related_name='periods', to='access.Alphabet'),
        ),
    ]
