# Generated by Django 4.0.2 on 2022-12-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0011_period_alphabet'),
    ]

    operations = [
        migrations.AddField(
            model_name='alphabet',
            name='sources',
            field=models.TextField(blank=True, null=True),
        ),
    ]
