# Generated by Django 4.0.2 on 2022-12-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0012_alphabet_sources'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitizationStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('process_name', models.CharField(max_length=100)),
                ('added_by', models.CharField(max_length=100)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pas de digitizare',
                'verbose_name_plural': 'Pasi de digitizare',
            },
        ),
    ]
