# Generated by Django 4.0.2 on 2022-12-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0013_digitizationstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrmodel',
            name='sources',
            field=models.TextField(blank=True, null=True),
        ),
    ]
