# Generated by Django 4.0.2 on 2022-12-23 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0015_rename_document_digidocument_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='digidocument',
            options={'verbose_name': 'Document digitizate', 'verbose_name_plural': 'Documente digitizate'},
        ),
    ]
