# Generated by Django 4.0.2 on 2022-12-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0016_alter_digidocument_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digidocument',
            name='file',
        ),
        migrations.RemoveField(
            model_name='digidocument',
            name='ocr_model',
        ),
        migrations.AddField(
            model_name='digidocument',
            name='ocr_model',
            field=models.ManyToManyField(to='access.OCRModel'),
        ),
        migrations.RemoveField(
            model_name='digidocument',
            name='postprocessing_engine',
        ),
        migrations.AddField(
            model_name='digidocument',
            name='postprocessing_engine',
            field=models.ManyToManyField(to='access.PostprocessingEngine'),
        ),
        migrations.RemoveField(
            model_name='digidocument',
            name='preprocessing_engine',
        ),
        migrations.AddField(
            model_name='digidocument',
            name='preprocessing_engine',
            field=models.ManyToManyField(to='access.PreprocessingEngine'),
        ),
    ]
