# Generated by Django 4.0.2 on 2022-12-23 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0017_remove_digidocument_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digidocument',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='access.file'),
        ),
    ]
