# Generated by Django 4.0.2 on 2022-12-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0019_instrumentsandresources_remove_digidocument_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentsandresources',
            name='app_file',
            field=models.FileField(blank=True, null=True, upload_to='apps/'),
        ),
        migrations.AddField(
            model_name='instrumentsandresources',
            name='type',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
