# Generated by Django 4.0.2 on 2022-12-23 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0021_alter_instrumentsandresources_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='digidocument',
            options={'verbose_name': 'Document digitizat', 'verbose_name_plural': 'Documente digitizate'},
        ),
        migrations.AlterModelOptions(
            name='digitizationstep',
            options={'verbose_name': 'Pas de digitizare', 'verbose_name_plural': 'Pași de digitizare'},
        ),
        migrations.AlterModelOptions(
            name='exceptiondictionary',
            options={'verbose_name': 'Dicționar de excepții', 'verbose_name_plural': 'Dicționare de excepții'},
        ),
        migrations.AlterModelOptions(
            name='exceptiondictionaryentry',
            options={'verbose_name': 'Excepție', 'verbose_name_plural': 'Excepții'},
        ),
        migrations.AlterModelOptions(
            name='instrumentsandresources',
            options={'verbose_name': 'Instrument și resurse', 'verbose_name_plural': 'Instrumente și resurse'},
        ),
        migrations.AlterModelOptions(
            name='ocrmodel',
            options={'verbose_name': 'Model OCR', 'verbose_name_plural': 'Modele OCR'},
        ),
    ]
