# Generated by Django 4.0.1 on 2022-01-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
        migrations.AlterField(
            model_name='file',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/documents/'),
        ),
    ]
