# Generated by Django 4.1.4 on 2022-12-19 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0007_rename_word_exceptiondictionaryentry_translit_word_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exceptiondictionaryentry',
            old_name='translit_word',
            new_name='correct_word',
        ),
    ]
