# Generated by Django 4.0.2 on 2022-12-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0009_alphabet_exceptiondictionary_period_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exceptiondictionary',
            options={'verbose_name': 'Dicționar de excepții', 'verbose_name_plural': 'Dictionare de excepții'},
        ),
        migrations.AlterModelOptions(
            name='exceptiondictionaryentry',
            options={'verbose_name': 'Exceptie', 'verbose_name_plural': 'Exceptii'},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'Fișier', 'verbose_name_plural': 'Fișiere'},
        ),
        migrations.AlterModelOptions(
            name='postprocessingenginemodule',
            options={'verbose_name': 'Modul de postprocesare', 'verbose_name_plural': 'Module de postprocesare'},
        ),
        migrations.AlterModelOptions(
            name='preprocessingengine',
            options={'verbose_name': 'Motor de preprocesare', 'verbose_name_plural': 'Motoare de preprocesare'},
        ),
        migrations.AlterModelOptions(
            name='preprocessingenginemodule',
            options={'verbose_name': 'Modul de preprocesare', 'verbose_name_plural': 'Module de preprocesare'},
        ),
        migrations.AddField(
            model_name='file',
            name='added_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='modified_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='exceptiondictionaryentry',
            name='added_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
