# Generated by Django 4.0.2 on 2022-12-23 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0014_ocrmodel_sources'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='DigiDocument',
        ),
        migrations.RenameField(
            model_name='digidocument',
            old_name='digital_object',
            new_name='digi_object',
        ),
    ]
