# Generated by Django 4.0.2 on 2022-12-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0018_digidocument_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentsAndResources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('api', models.CharField(max_length=100)),
                ('added_by', models.CharField(max_length=100)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Instrument si resurse',
                'verbose_name_plural': 'Instrumente si resurse',
            },
        ),
        migrations.RemoveField(
            model_name='digidocument',
            name='file',
        ),
    ]
