# Generated by Django 4.0.2 on 2022-12-23 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0022_alter_digidocument_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alphabet',
            options={'verbose_name': 'Alfabet', 'verbose_name_plural': 'Alfabete'},
        ),
    ]
