# Generated by Django 4.0.2 on 2022-12-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0023_alter_alphabet_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='ocr_text',
        ),
        migrations.RemoveField(
            model_name='file',
            name='original_image_S3',
        ),
        migrations.RemoveField(
            model_name='file',
            name='original_image_local',
        ),
        migrations.RemoveField(
            model_name='file',
            name='preprocessed_image_S3',
        ),
        migrations.RemoveField(
            model_name='file',
            name='preprocessed_image_local',
        ),
        migrations.RemoveField(
            model_name='file',
            name='transliterated_text',
        ),
        migrations.AddField(
            model_name='file',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/documents/'),
        ),
    ]
